### PR TITLE
MS-1410 - updated Sceneform resources with streem_ prefix

### PR DESCRIPTION
**Pull request by kurteous**
and updated Sceneform version to 2.0.2.

### CODE REVIEW

**Review by garyp — APPROVED** [review]
A few minor suggestions:

* You've got one `e` too many in `sceneformsrc/sceneform/src/main/res/raw/streeem_sceneform_opaque_colored_material.matc`
* Rename `sceneformsrc/sceneform/sampleData/streem_small_empty_house_2k.exr` to `sceneformsrc/sceneform/sampleData/streem_sceneform_small_empty_house_2k.exr` so that all resources have a consistent `streem_sceneform_` prefix
* Add the `resourcePrefix` option to the `android` block in all of the gradle files so that Android Studio will help enforce `streem_sceneform_` as the prefix for new resources: https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/dsl/CommonExtension#resourceprefix.

Also, we should probably do a similar exercise in the Streem SDK and make sure all resources have a consistent `streem_sdk_` prefix.

**Comment by kurteous** [comment]
> A few minor suggestions:
> 
> * You've got one `e` too many in `sceneformsrc/sceneform/src/main/res/raw/streeem_sceneform_opaque_colored_material.matc`
> * Rename `sceneformsrc/sceneform/sampleData/streem_small_empty_house_2k.exr` to `sceneformsrc/sceneform/sampleData/streem_sceneform_small_empty_house_2k.exr` so that all resources have a consistent `streem_sceneform_` prefix
> * Add the `resourcePrefix` option to the `android` block in all of the gradle files so that Android Studio will help enforce `streem_sceneform_` as the prefix for new resources: https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/dsl/CommonExtension#resourceprefix.
> 
> Also, we should probably do a similar exercise in the Streem SDK and make sure all resources have a consistent `streem_sdk_` prefix.

Thanks for the review! Suggestions are all implemented, though I noticed that adding `resourcePrefix = "streem_sceneform_"` to both `build.gradle.kts` files here doesn't seem to trigger any lint warnings when I run `./gradlew lint` with a non-conforming resource. I'm not sure how to make this do something useful.

**Comment by garyp** [comment]
> Thanks for the review! Suggestions are all implemented, though I noticed that adding `resourcePrefix = "streem_sceneform_"` to both `build.gradle.kts` files here doesn't seem to trigger any lint warnings when I run `./gradlew lint` with a non-conforming resource. I'm not sure how to make this do something useful.

Hmm. The docs for that option do say that it is only used by Android Studio. I thought that would've included `./gradlew lint`, but perhaps they literally mean that only Android Studio's code inspection will use this setting 🤷‍♂️ Could try running Android Studio's "Inspect Code" and see if it flags the error. Or maybe create a string resource in Android Studio without the prefix and see if it gets a red underline or something?

**Comment by kurteous** [comment]
> > Thanks for the review! Suggestions are all implemented, though I noticed that adding `resourcePrefix = "streem_sceneform_"` to both `build.gradle.kts` files here doesn't seem to trigger any lint warnings when I run `./gradlew lint` with a non-conforming resource. I'm not sure how to make this do something useful.
> 
> Hmm. The docs for that option do say that it is only used by Android Studio. I thought that would've included `./gradlew lint`, but perhaps they literally mean that only Android Studio's code inspection will use this setting 🤷‍♂️ Could try running Android Studio's "Inspect Code" and see if it flags the error. Or maybe create a string resource in Android Studio without the prefix and see if it gets a red underline or something?

Well now, after testing it some more I see that `./gradlew lint` _does_ in fact flag misnamed files and string names. Not sure why it didn't before. So this is good, because I assume that means CI will catch issues too. In the case of bad string names Android Studio does show them in red. It doesn't alert you to misnamed files in the IDE, however, unless you manually run "Inspect Code". In any case, I'm glad it's working as you expected it to work.

**Pull request merged**
